steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/demo-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'demo-app', '--image', 'gcr.io/$PROJECT_ID/your-image-name', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
